---
driver:
  name: vagrant

provisioner:
  name: chef_zero_scheduled_task
  require_chef_omnibus: 12.8.1

platforms:
- name: centos-6.7
  driver_config:
    box:     opscode-centos-6.7

- name: centos-7.2
  driver_config:
    box:     criteo-centos-7.2-core

- name: windows-2012r2
  driver_config:
    box: criteo-windows-2012r2-standard

suites:
  - name: default
    run_list:
      - recipe[test]
